# Change these first
owner: JoMei9019-real # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Anturnia
    url: https://Anturnia.net
    icon: https://i.postimg.cc/X7MQ3kMd/Hcs-IKQAx-200x200.png
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Status
    url: https://status.jomei.tk
  - name: DNS
    check: "tcp-ping"
    url: $IP
    port: 80

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jomei.tk
  # baseUrl: /your-repo-name
  logoUrl: https://i.imgur.com/7D1lrtH.png
  name: Status
  introTitle: "**Upptime** for Anturnia.net / JoMei9019"
  introMessage: This is a simple status page :)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: http://www.jmstracker.tk/github/error.html
    - title: Discord
      href: https://dc.anturnia.net

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
